name: guild_test_joke
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  connectivity_plus: 4.0.2

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  flutter_riverpod: 2.3.6
  fluttertoast: 8.2.2
  http: 1.1.0
  intl: 0.18.0
  go_router: 10.0.0
  google_fonts: 5.1.0


dev_dependencies:
  flutter_driver:
    sdk: flutter

  # flutter_test:
  #   sdk: flutter
  
  test: 1.24.5
  very_good_analysis: 5.0.0+1

dependency_overrides: 
  matcher: 0.12.15
  test_api: 0.5.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - google_fonts/

    - assets/images/joke_logo.png
