name: guild_test_joke
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  intl: 0.18.0
  flutter_riverpod: 2.3.6
  http: 1.1.0
  google_fonts: 5.1.0
  go_router: 10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  very_good_analysis: 5.0.0+1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - google_fonts/
